### PR TITLE
Add release 0.5.0 metadata

### PR DESCRIPTION
**Pull request by jisnardo**
**What this PR does / why we need it**:

Fix Error: invalid provider metadata: version v0.5.0 (one of the available versions) for the provider rke2-bootstrap-system/bootstrap-rke2-bootstrap does not match any release series

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

https://github.com/rancher/cluster-api-provider-rke2/issues/374

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Review by Danil-Grigorev — APPROVED** [review]

**Comment by salasberryfin** [comment]
This is a duplicate of #372

**Comment by Danil-Grigorev** [comment]
@salasberryfin This change is self contained and is good to go. E2E tests will have to be updated on release `0.5.1` after so #372 will have to be updated separately. I’d be in favor of merging this.

**Comment by salasberryfin** [comment]
Don't have a preference. Just updated E2E in the same PR because that's what I remember we did in past releases, but I'm happy to merge this as a stand-alone change and fix the other PR later :+1:

**Review by salasberryfin — APPROVED** [review]

**Comment by alexander-demicev** [comment]
@Danil-Grigorev seems like CI will fail here until we merge E2E changes here https://github.com/rancher/cluster-api-provider-rke2/pull/372

**Comment by Danil-Grigorev** [comment]
We eventually fixed this in https://github.com/rancher/cluster-api-provider-rke2/pull/372 as it needed e2e tests update, closing, thanks for the PR

**Pull request closed without merging**
