### PR TITLE
add securityContext to the manager containers

### LINKED ISSUE #384: Cannot install RKE2 bootstrap and control-plane providers into an RKE2 cluster with cisProfile set
**What happened:**
I used this provider to create an RKE2 cluster with the `cisProfile` set, but was unable to then pivot my management cluster to it since `clusterctl init --bootstrap rke2 --control-plane rke2` was erroring out due to no `securityContext` being set for the manager pods for the rke2-bootstrap-controller-manager and rke2-control-plane-manager:
```
$ clusterctl init --bootstrap rke2 --control-plane rke2 --kubeconfig=kubeconfig-rke2-mgmt-cluster.yaml
Fetching providers
Skipping installing cert-manager as it is already installed
Installing Provider="bootstrap-rke2" Version="v0.1.1" TargetNamespace="rke2-bootstrap-system"
[KubeAPIWarningLogger] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "manager" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "manager" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Installing Provider="control-plane-rke2" Version="v0.1.1" TargetNamespace="rke2-control-plane-system"
[KubeAPIWarningLogger] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "manager" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "manager" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**How to reproduce it:** 
- From an existing management cluster, create an RKE2 cluster (I used `--kubernetes-version v1.29.1+rke2r1`) with `cis-1.23` for both `RKE2ConfigTemplate.spec.template.spec.agentConfig.cisProfile` and `RKE2ControlPlane.spec.agentConfig.cisProfile`
- obtain the generated kubeconfig for the new cluster: `clusterctl get kubeconfig rke2-mgmt-cluster > kubeconfig.yaml`
- `clusterctl init --kubeconfig=kubeconfig.yaml`
- `clusterctl init --bootstrap rke2 --control-plane rke2 --kubeconfig=kubeconfig.yaml` <-- this part will fail due to missing `securityContexts`

**Anything else you would like to add:**
I was able to successfully install the bootstrap and control-plane providers and then pivot my management cluster into the RKE2 cluster by using a local version of the providers that included this in both manager containers:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
```

**Environment:**

- rke provider version: v0.5.0

### PR DESCRIPTION
**Pull request by AshleyDumaine**
kind/bug

**What this PR does / why we need it**: Without `securityContext` set for the manager containers, RKE2 bootstrap and control-plane providers cannot be installed into an RKE2 cluster with cis-profile set (e.g. creating a hardened RKE2 cluster and pivoting the management cluster into it).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: 
Fixes #384

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@AshleyDumaine thanks for the contribution. 
I was checking the previous releases of the CAPI, and noticed they introduced same changes in release-1.4 minor version. As we strive to align with upstream and CAPI in general, can I ask you to take a look at https://github.com/kubernetes-sigs/cluster-api/pull/7831/files#diff-8d4b80dac52bef6a87376c16699a47555f567a9c7b68408965e37b68dedee6cb and add the missing bits in this patch?

**Comment by AshleyDumaine** [comment]
> @AshleyDumaine thanks for the contribution. I was checking the previous releases of the CAPI, and noticed they introduced same changes in release-1.4 minor version. As we strive to align with upstream and CAPI in general, can I ask you to take a look at https://github.com/kubernetes-sigs/cluster-api/pull/7831/files#diff-8d4b80dac52bef6a87376c16699a47555f567a9c7b68408965e37b68dedee6cb and add the missing bits in this patch?

Sounds good, just pushed the update 👍

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
@alexander-demicev @salasberryfin @Danil-Grigorev

**Review by alexander-demicev — APPROVED** [review]
thanks!

**Pull request merged**
